const Actions = {
    SIGNUPREQUEST:'SIGNUPREQUEST',
     SIGNUPREQUESTSUCCESS:'SIGNUPREQUESTSUCCESS',
      SIGNUPREQUESTFAILED:'SIGNUPREQUESTFAILED',

      LOGINREQUEST:' LOGINREQUEST',
      LOGINREQUESTSUCCESS:' LOGINREQUESTSUCCESS',
      LOGINREQUESTFAILED:' LOGINREQUESTFAILED'
}


export default Actions;