const Actions = {
    SIGNUPREQUEST:'SIGNUPREQUEST',
     SIGNUPREQUESTSUCCESS:'SIGNUPREQUESTSUCCESS',
      SIGNUPREQUESTFAILED:'SIGNUPREQUESTFAILED',

      LOGINREQUEST:' LOGINREQUEST',
      LOGINREQUESTSUCCESS:' LOGINREQUESTSUCCESS',
      LOGINREQUESTFAILED:' LOGINREQUESTFAILED',

      
      LOGOUTREQUEST:'LOGOUTREQUEST',
      LOGOUTREQUESTSUCCESS:'LOGOUTREQUESTSUCCESS',
      LOGOUTREQUESTFAILED:'LOGOUTREQUESTFAILED',

     ADDPRODUCTREQUEST :'ADDPRODUCTREQUEST',
    ADDPRODUCTREQUESTSUCCESS :'ADDPRODUCTREQUESTSUCCESS',
   ADDPRODUCTREQUESTFAILED:'ADDPRODUCTREQUESTFAILED',


   VIEWPRODUCTREQUEST : 'VIEWPRODUCTREQUEST',
  VIEWPRODUCTREQUESTSUCCESS :'VIEWPRODUCTREQUESTSUCCESS',
  VIEWPRODUCTREQUESTFAILED:'VIEWPRODUCTREQUESTFAILED',
    BIDDINREQUEST:'BIDDINREQUEST',
   BIDDINREQUESTSUCCESS :'BIDDINREQUESTSUCCESS',
BIDDINREQUESTFAILED:'BIDDINREQUESTFAILED'
}


export default Actions;